Models/FilesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using jQuery_File_Upload.MVC5.Helpers;
namespace jQuery_File_Upload.MVC5.Models
{
    public class FilesViewModel
    {
        public ViewDataUploadFilesResult[] Files { get; set; }
    }
}

Models/fg.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace jQuery_File_Upload.MVC5.Models
{
    public static class fg
    {
        public static string GenerateUniqueCode()
        {
            return DateTime.Now.ToString("ddMMMyyyyhhmmss");
        }
    }
}

Controllers/FileUploadController.cs
using DataModel;
using jQuery_File_Upload.MVC5.Helpers;
using jQuery_File_Upload.MVC5.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace jQuery_File_Upload.MVC5.Controllers
{
    public class FileUploadController : Controller
    {
        FilesHelper filesHelper;
        String tempPath = "~/somefiles/";
        String serverMapPath = "~/Files/somefiles/";
        private string StorageRoot
        {
            get { return Path.Combine(HostingEnvironment.MapPath(serverMapPath)); }
        }
        private string UrlBase = "/Files/somefiles/";
        String DeleteURL = "/FileUpload/DeleteFile/?file=";
        String DeleteType = "GET";
        public FileUploadController()
        {
           filesHelper = new FilesHelper(DeleteURL, DeleteType, StorageRoot, UrlBase, tempPath, serverMapPath);
        }
      
        public ActionResult Index(string id = "")
        {
            // set id if empty
            if (string.IsNullOrWhiteSpace(id))
            {
                id = DateTime.Now.ToString("ddMMMyyyyhhmmss");
            }

            // pass identifier to view
            ViewBag.Id = id;

            return View();
        }
        public ActionResult Show()
        {
            JsonFiles ListOfFiles = filesHelper.GetFileList("");
            var model = new FilesViewModel()
            {
                Files = ListOfFiles.files
            };
          
            return View(model);
        }

        public ActionResult Edit(string id = "")
        {

            ViewBag.Id = id;

            return View();
        }

        [HttpPost]
        public JsonResult Upload()
        {
            var resultList = new List<ViewDataUploadFilesResult>();
           
            var CurrentContext = HttpContext;
            string idd = Request.Form["idd"];

            filesHelper.UploadAndShowResults(CurrentContext, resultList, idd);
            JsonFiles files = new JsonFiles(resultList);

            bool isEmpty = !resultList.Any();
            if (isEmpty)
            {
                return Json("Error ");
            }
            else
            {
                return Json(files);
            }
        }
        public JsonResult GetFileList(string id = "")
        {

            // set id if empty
            if (string.IsNullOrWhiteSpace(id))
            {
                id = DateTime.Now.ToString("ddMMMyyyyhhmmss");
            }

            // pass identifier to view
            ViewBag.Id = id;

            var list=filesHelper.GetFileList(id);
            return Json(list,JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public JsonResult DeleteFile(string file)
        {
            filesHelper.DeleteFile(file);
            return Json("OK", JsonRequestBehavior.AllowGet);
        }
       
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace jQuery_File_Upload.MVC5.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Views/FileUpload/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<!-- blueimp File Upload & Gallery styles -->
@Styles.Render("~/Content/jQuery-File-Upload")

<script>
    var $form = null;
    $(function () {

        $form = $('#fileupload').fileupload({
            dataType: 'json'
        });

    });
    $('#fileupload').addClass('fileupload-processing');
 
    var id = '@ViewBag.Id';

    $.ajax({
         type: 'GET',
        contentType: "application/json; charset=utf-8",
        url: '/FileUpload/GetFileList?id=' + id,
        success: function (data) {


            $('#fileupload').fileupload('option', 'done').call($('#fileupload'), $.Event('done'), { result: { files: data.files } })
            $('#fileupload').removeClass('fileupload-processing');
        }

    }

    );
</script>

@Html.Partial("_Files")

@Scripts.Render("~/bundles/jQuery-File-Upload")

Views/FileUpload/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!-- blueimp File Upload & Gallery styles -->
@Styles.Render("~/Content/jQuery-File-Upload")

@*<script>

        $(function () {
            $('#fileUpload').fileupload({
                dataType: 'json',
                done: function (e, data) {
                    $.each(data.result.files, function (index, file) {
                        $('<p/>').text(file.name).appendTo(document.body);
                    });
                }
            });
        });
    </script>*@

<script>
    var $form = null;
    $(function () {

        $form = $('#fileupload').fileupload({
            dataType: 'json',
            maxNumberOfFiles: 5,
            acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
            maxFileSize: 1048576
            // autoUpload: true
        });

    });
    $('#fileupload').addClass('fileupload-processing');

</script>
@Html.Partial("_Files")


@Scripts.Render("~/bundles/jQuery-File-Upload")

Views/FileUpload/Show.cshtml
@model jQuery_File_Upload.MVC5.Models.FilesViewModel
@using jQuery_File_Upload.MVC5.Helpers


@{
    ViewBag.Title = "Show";
}
<!-- blueimp File Upload & Gallery styles -->
@Styles.Render("~/Content/jQuery-File-Upload")

<h2>Show</h2>
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<div id="links">

    @if (@Model.Files != null && @Model.Files.Length!=0)
    {
        foreach (ViewDataUploadFilesResult file in @Model.Files)
        {

            if (file.type.Equals("video/mp4"))
            {
             
                <a href="@file.url" title="@file.name" type="video/mp4" data-description="This is a movie."><img src="@file.thumbnailUrl" alt="@file.name"></a>


            }
            else
            {
                <a href="@file.url" title="@file.name" data-description="This is a image."><img src="@file.thumbnailUrl" alt="@file.name"></a>
            }

        }
    }
    else
    {
<p>No files</p>
    }
    <!--Your files goes here-->
</div>
<script>

    document.getElementById('links').onclick = function (event) {
        event = event || window.event;
        var target = event.target || event.srcElement,
            link = target.src ? target.parentNode : target,
            options = { index: link, event: event },
            links = this.getElementsByTagName('a');
        blueimp.Gallery(links, options);

    };
</script>
@Scripts.Render("~/bundles/Blueimp-Gallerry2")

Views/FileUpload/_Files.cshtml
<h2>File Uploader</h2>

<form id="fileupload" method="POST" enctype="multipart/form-data" data-url="@Url.Action("Upload","FileUpload")">
    
    <input type="hidden" value="@ViewBag.Id" name="idd" />

    <div class="row fileupload-buttonbar">
        <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add files...</span>
                    <input type="file" name="files[]" multiple>
                </span>
                @*<button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>*@
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
                <button type="button" class="btn btn-danger delete">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                
                <!-- The global file processing state -->
                <span class="fileupload-process"></span>
            </div>
            <!-- The global progress state -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The global progress state -->
        <div class="col-lg-5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-success" style="width:0%;"></div>
            </div>
            <!-- The extended global progress state -->
            <div class="progress-extended">&nbsp;</div>
        </div>
    
    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
</form>

<br>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
            <button class="btn btn-primary start" disabled>
                <i class="glyphicon glyphicon-upload"></i>
                <span>Start</span>
            </button>
            {% } %}
            {% if (!i) { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="http://localhost:51475{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
            <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
            <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}" {% if (file.deletewithcredentials) { %} data-xhr-fields='{"withCredentials":true}' {% } %}>
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
            </button>
            
            {% } else { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>

<div class="panel panel-default extraMsg">
    <div class="panel-heading">
        <h3 class="panel-title">File Upload Notes</h3>
    </div>
    <div class="panel-body">
        <ul>
            <li>The maximum file size for uploads is <strong>1 MB</strong>.</li>
            <li>Only 5 files can be uploaded at once.</li>
            <li>Only image files (<strong>JPG, GIF, PNG</strong>) are allowed.</li>
            <li>You can drag and drop your files if you so desire</li>
        </ul>
    </div>
</div>

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1> jQuery-File-Upload.MVC5</h1>
    <p class="lead">Simple implementation of Blueimp jQuery File Upload Plugin using ASP.NET MVC5 </p>
    <p><a href="https://github.com/TheKalin/jQuery-File-Upload.MVC5" class="btn btn-primary btn-lg">Check it on github&raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>blueimp/jQuery-File-Upload</h2>
        <p>
            File Upload widget with multiple file selection, drag&drop support, progress bar, validation and preview images, audio and video for jQuery. Supports cross-domain, chunked and resumable file uploads. Works with any server-side platform (Google App Engine, PHP, Python, Ruby on Rails, Java, etc.) that supports standard HTML form file uploads.
        </p>
        <p><a class="btn btn-default" href="https://github.com/blueimp/jQuery-File-Upload/">Go &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>blueimp/Gallery</h2>
        <p>blueimp Gallery is a touch-enabled, responsive and customizable image & video gallery, carousel and lightbox, optimized for both mobile and desktop web browsers. It features swipe, mouse and keyboard navigation, transition effects, slideshow functionality, fullscreen support and on-demand content loading and can be extended to display additional…</p>
        <p><a class="btn btn-default" href="https://blueimp.github.io/jQuery-File-Upload/index.html">Go&raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2> John-ph C#: Image resize, convert, and save</h2>
        <p>C#: Image resize, convert, and save <p><a class="btn btn-default" href="http://www.codeproject.com/Tips/552141/Csharp-Image-resize-convert-and-save">Go&raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>teambox/Free-file-icons</h2>
        <p>Platform-agnostic icons for audio, image, programming and office files  <p><a class="btn btn-default" href="https://github.com/teambox/Free-file-icons">Go&raquo;</a></p>
    </div>

   
    <div class="col-md-4">
        <h2> maxpavlov/jQuery-File-Upload.MVC3</h2>
        <p>An example of how to use jQuery-File-Upload plugin with ASP.NET MVC3   <p><a class="btn btn-default" href="https://github.com/maxpavlov/jQuery-File-Upload.MVC3">Go&raquo;</a></p>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - File Uploader</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
</head>
<body>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("jQuery-File-Upload.MVC5", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Show", "Show", "FileUpload")</li>
                    <li>@Html.ActionLink("Add", "Index", "FileUpload")</li>
                    <li>@Html.ActionLink("Edit", "Edit", "FileUpload")</li>
                </ul>
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - jQuery-File-Upload.MVC5</p>
        </footer>
    </div>
  

    
   
    @RenderSection("scripts", required: false)
</body>
</html>